# Generated by Django 5.1.2 on 2024-10-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите дату и время окончания рассылки",
                null=True,
                verbose_name="Окончание рассылки",
            ),
        ),
    ]
