# Generated by Django 5.1.2 on 2024-10-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailing_end_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Начало рассылки"),
        ),
    ]
